version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/app"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/client"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/src/old"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
